name: Release pipeline

on:
  release:
    types:
      - created

jobs:
  release-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7 ]

    env:
      DATABRICKS_HOST: ${{{{ secrets.DATABRICKS_HOST }}}}
      DATABRICKS_TOKEN:  ${{{{ secrets.DATABRICKS_TOKEN }}}}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{{{ runner.os }}}}-pip-${{{{ hashFiles('**/unit-requirements.txt') }}}}
          restore-keys: |
            ${{{{ runner.os }}}}-pip-${{{{ hashFiles('**/unit-requirements.txt') }}}}
            ${{{{ runner.os }}}}-pip-

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r unit-requirements.txt
          pip install -U tools/dbx-0.7.0-py3-none-any.whl

      - name: Prepare profile
        run: |
          echo "[{profile}]" >> ~/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg

      - name: Build artifact
        run: |
          python setup.py bdist_wheel

      - name: Perform deployment
        run: |
          dbx deploy

