name: test

on:
  push:
    branches-ignore:
      - 'master' # the branch will be tested before push to master
    tags-ignore:
      - '*.*'
    paths-ignore:
      - 'README.md' # if we change documentation only, we don't need to run tests

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7.5]

    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      GH_PWD: ${{ secrets.GH_PWD }}
      DBX_AZURE_HOST: ${{ secrets.DBX_AZURE_HOST }}
      DBX_AZURE_TOKEN:  ${{ secrets.DBX_AZURE_TOKEN }}

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip
      run: |
        python -m pip install --upgrade pip

    - name: Install test dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests


